name: firstworkflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hi, how are you"
      - name: Print Goodvibes
        run: echo "Goodvibes"
